export const ErrorCodes = {
  IR_PARSE_ERROR: "IR_PARSE_ERROR",
  IR_SCHEMA_ERROR: "IR_SCHEMA_ERROR",
  IR_UNKNOWN_FIELD: "IR_UNKNOWN_FIELD",
  IR_MISSING_REQUIRED_FIELD: "IR_MISSING_REQUIRED_FIELD",
  IR_DUPLICATE_NODE_ID: "IR_DUPLICATE_NODE_ID",
  IR_DUPLICATE_EDGE_ID: "IR_DUPLICATE_EDGE_ID",
  IR_UNKNOWN_EDGE_FROM: "IR_UNKNOWN_EDGE_FROM",
  IR_UNKNOWN_EDGE_TO: "IR_UNKNOWN_EDGE_TO",
  IR_CYCLE_DETECTED: "IR_CYCLE_DETECTED",
  IR_INVALID_NODE_ROLE: "IR_INVALID_NODE_ROLE",
  IR_UNSUPPORTED_KIND: "IR_UNSUPPORTED_KIND",
  IR_UNSUPPORTED_DIRECTION: "IR_UNSUPPORTED_DIRECTION"
} as const;

export type DiagnosticCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
